spring.application.name=projection-service
server.port=${SERVER_PORT:8087}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/projectiondb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:projection}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:projection}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:projection-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
