spring.application.name=payment-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/paymentdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:payment}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:payment-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topics.order-created=saga.order.order_created
app.kafka.topics.order-created-dlt=saga.order.order_created-dlt
