spring.application.name=order-service
server.port=${SERVER_PORT:8083}

spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/orderdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:order}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:order}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:order-service}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.tahaberkamcadev.order_service.kafka.event.inbound.InventoryEvent
