spring.application.name=inventory-service
server.port=8082

# PostgreSQL (compose: 5434 - inventorydb)
spring.datasource.url=jdbc:postgresql://localhost:5434/inventorydb
spring.datasource.username=inventory
spring.datasource.password=inventory

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka (compose: localhost:9093)
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.consumer.group-id=inventory-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Pagination settings
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=30



app.kafka.topics.reserve-request=saga.inventory.reserve.request
app.kafka.topics.reserved=saga.inventory.reserved
app.kafka.topics.reserve-failed=saga.inventory.reserve.failed
app.kafka.topics.confirm-request=saga.inventory.confirm.request
app.kafka.topics.confirmed=saga.inventory.confirmed
app.kafka.topics.release-request=saga.inventory.release.request
app.kafka.topics.released=saga.inventory.released
