spring.application.name=inventory-service
server.port=${SERVER_PORT:8082}

spring.docker.compose.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventorydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:inventory}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:inventory-service}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.enable-auto-commit=false

app.kafka.topics.order-cancelled=saga.order.order_cancelled
app.kafka.topics.order-cancelled-dlt=saga.order.order_cancelled-dlt

app.gateway.secret=${GATEWAY_SECRET}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=${spring.application.name}
info.app.name=inventory-service
info.app.description=Inventory and purchase saga entry point
management.endpoint.health.probes.enabled=true
