spring.application.name=inventory-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventorydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:inventory}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:inventory-service}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.enable-auto-commit=false

app.kafka.topics.reserve-request=saga.inventory.reserve.request
app.kafka.topics.review-request=saga.inventory.review.request
app.kafka.topics.reserved=saga.inventory.reserved
app.kafka.topics.reserve-failed=saga.inventory.reserve.failed
app.kafka.topics.confirm-request=saga.inventory.confirm.request
app.kafka.topics.confirmed=saga.inventory.confirmed
app.kafka.topics.release-request=saga.inventory.release.request
app.kafka.topics.released=saga.inventory.released

app.kafka.topics.reserve-request-dlt=saga.inventory.reserve.request.DLT
app.kafka.topics.review-request-dlt=saga.inventory.review.request.DLT

app.gateway.secret=${GATEWAY_SECRET}
