spring.application.name=review-service
server.port=${SERVER_PORT:8086}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/reviewdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:review}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:review}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.gateway.secret=${GATEWAY_SECRET}
